[project]
authors = ["David W.H. Swenson <dwhs@hyperblazer.net>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "cloud-cron"
platforms = ["osx-64", "osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
fmt = "tofu fmt -recursive"
validate = "tofu validate"
pre-commit = "pre-commit run --all-files"

[dependencies]
opentofu = "*"
python = "*"
boto3 = "*"
jinja2 = "*"

pytest = "*"
pytest-cov = "*"
moto = "*"
pre-commit = "*"
